# Generated by Django 4.2.1 on 2023-06-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catalog_id_number',
            field=models.IntegerField(default=0),
        ),
    ]
